import math 
a = ( input ( ) )
b = ( input ( ) )
print ( float ( a ) - float ( b ) )
print ( float ( b ) - float ( a ) )
print ( float ( a ) * float ( b ) )
print ( float ( a ) // float ( b ) )
print ( float ( b ) / float ( a ) )
print ( float ( a ) ** float ( b ) )
print ( float ( b ) ** float ( a ) )
print ( math.cos ( int ( a ) ) )
print ( math.cos ( int ( b ) ) )
print ( math.sin ( int ( a ) ) )
print ( math.sin ( int ( b ) ) )
print ( ( a ) + ( b ) )
