import math 
a = float ( input ( ) )
b = float ( input ( ) )
print ( a + b )
print ( a - b )
print ( b - a ) 
print ( a * b ) 
print ( a // b ) 
print ( b / a ) 
print ( a ** b ) 
print ( b ** a ) 
print ( math.cos ( a ) )
print ( math.cos ( b ) )
print ( math.sin ( a ) )
print ( math.sin ( b ) )
print ( str ( a ) + str ( b ) )
